spring:
  application:
    name: nexus-test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        format_sql: true
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false

  datasource:
    url: jdbc:postgresql://localhost:5432/nexus-test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.nexus: debug